export type FunnelTag = 'Lead Capture' | 'Booking' | 'Checkout' | 'Website'

export type Funnel = {
  file: string
  label: string
  tag: FunnelTag
  desc: string
  /** Public subfolder the HTML + thumbnail live under. Default 'funnels'. */
  dir?: 'funnels' | 'samples'
  /** A plain screenshot (3:4) used instead of the HTML page's thumbnail. */
  image?: string
}

/**
 * Screenshots for the "Pages and sites" reel on Projects. Look-only: the reel
 * spins and pops on hover, nothing opens. Files live in public/pages/ at 3:4
 * (600x800). While this list is empty the reel shows the placeholder sites.
 */
export const shot = (file: string, label: string): Funnel => ({
  file,
  label,
  tag: 'Website',
  desc: '',
  image: `/pages/${file}`,
})

export const pageShots: Funnel[] = [
  shot('oralin-dental.jpg', 'Oralin Dental Clinic website'),
  shot('omar-furniture.jpg', 'Omar furniture shopping app'),
  shot('travelnest-app.jpg', 'TheTravelNest travel app'),
  shot('pure-reception.jpg', 'Pure Reception social posts'),
  shot('luxora-fashion.jpg', 'Luxora fashion app'),
  shot('tillamook-home.jpg', 'Home rental listing card'),
  shot('grocery-app.jpg', 'Grocery delivery app'),
  shot('guitar-product.jpg', 'Guitar product card'),
  shot('ride-concept.jpg', 'Ride-hailing app redesign'),
  shot('taskly-app.jpg', 'Taskly task manager app'),
]

/**
 * Your funnel pages and website samples. Every entry is a PLACEHOLDER page
 * generated by scripts/make-placeholder-sites.mjs.
 *
 * To add your own: drop the page's HTML in public/funnels/ (single pages) or
 * public/samples/ (full websites), add an entry here, then run
 * `node scripts/make-thumbs.mjs` to render its thumbnails.
 */

const funnel = (n: string, tag: FunnelTag): Funnel => ({
  file: `placeholder-funnel-${n}.html`,
  label: `Placeholder Funnel ${n}`,
  tag,
  desc: 'PLACEHOLDER - tell me what to put here: who this page was for and what it does.',
})

const site = (n: string): Funnel => ({
  file: `placeholder-site-${n}.html`,
  label: `Placeholder Website ${n}`,
  tag: 'Website',
  desc: 'PLACEHOLDER - tell me what to put here: the client, the industry, and what the site had to do.',
  dir: 'samples',
})

export const gymFunnel: Funnel[] = [
  funnel('01', 'Lead Capture'),
  funnel('02', 'Checkout'),
  funnel('03', 'Lead Capture'),
]

export const bookingFunnel: Funnel[] = [
  funnel('04', 'Booking'),
  funnel('05', 'Booking'),
  funnel('06', 'Booking'),
]

export const websiteFunnel: Funnel[] = ['01', '02', '03', '04', '05', '06'].map(site)

/**
 * Tag -> color map. Brand-external colors that identify the page type, passed
 * to CSS via an inline --tag-color custom property.
 */
export const tagColors: Record<FunnelTag, string> = {
  'Lead Capture': '#8b5cf6',
  Booking: '#ec4899',
  Checkout: '#f59e0b',
  Website: '#FF7A1A',
}
